Repository kingsleyadam/local-abbfreeathome-hass, pull requests merged in 2024-10, with the labels that each got.

#1 Adds zeroconf support to the integration
  custom_components/abbfreeathome-ci/config_flow.py
  custom_components/abbfreeathome-ci/manifest.json
Labels: enhancement

#2 Make a number of adjustments to the integration setup
  custom_components/abbfreeathome-ci/__init__.py
  custom_components/abbfreeathome-ci/config_flow.py
  custom_components/abbfreeathome-ci/manifest.json
  custom_components/abbfreeathome-ci/strings.json
  custom_components/abbfreeathome-ci/translations/en.json
Labels: enhancement

#3 Set description placeholders more globally
  custom_components/abbfreeathome-ci/config_flow.py
  custom_components/abbfreeathome-ci/manifest.json
Labels: bug

#4 Refine the config flow and text
  custom_components/abbfreeathome-ci/config_flow.py
  custom_components/abbfreeathome-ci/const.py
  custom_components/abbfreeathome-ci/manifest.json
  custom_components/abbfreeathome-ci/strings.json
  custom_components/abbfreeathome-ci/translations/en.json
Labels: enhancement

#6 Expose device info, close websocket properly
  README.md
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/switch.py
Labels: enhancement

#7 Bump local-abbfreeathome to 1.2.1
  custom_components/abbfreeathome_ci/manifest.json
Labels: bug

#10 Use the term SwitchActuator vs Switch
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/switch.py
Labels: enhancement

#12 Add SysAP as a new device, link switches to it
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/switch.py
Labels: enhancement

#14 Add a filter to the list of devices to integrate
  custom_components/abbfreeathome_ci/__init__.py
Labels: enhancement

#17 Adds new device dump service
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/const.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/services.yaml
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#18 Add WIRELESS_RF as allowed interface
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: bug

#19 Bump PyPi package to 1.3.2
  custom_components/abbfreeathome_ci/manifest.json
Labels: bug

#22 Implement diagnostics settings for integration
  README.md
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/const.py
  custom_components/abbfreeathome_ci/diagnostics.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/services.yaml
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#25 Adds support for sensor and binary sensor platforms
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/sensor.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/switch.py
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#26 Add new Event entity for sensor switch's
  README.md
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/event.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#28 Only add a new sensor if it has a value other than None
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/sensor.py
Labels: bug

#30 Adjust naming of sensors.
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/event.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/sensor.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: bug

#34 Add reconfigure integration flow.
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#35 Add options to include/exclude orphan nodes
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/const.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#36 Update readme for config options
  README.md
  custom_components/abbfreeathome_ci/manifest.json
Labels: documentation

#37 Fix broken domain
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/const.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: bug

#40 Add window/door sensor to integration
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/event.py
  custom_components/abbfreeathome_ci/sensor.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/switch.py
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#38 Add new light entity
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/light.py
Labels: enhancement

#43 Add smoke detector, carbon monoxide sensor
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#46 Adds new window position sensor
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/sensor.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#48 Add function, pairing to diagnostics, update readme.
  README.md
  custom_components/abbfreeathome_ci/diagnostics.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: documentation

#52 Implement Trigger as Button
  README.md
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/button.py
Labels: enhancement

#53 Add DesDoorRingingSensor to event sensor
  custom_components/abbfreeathome_ci/event.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#56 Use get_devices_by_class vs get_device_by_class
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/button.py
  custom_components/abbfreeathome_ci/event.py
  custom_components/abbfreeathome_ci/light.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/sensor.py
  custom_components/abbfreeathome_ci/switch.py
Labels: bug
