Repository kingsleyadam/local-abbfreeathome-hass, pull requests merged in 2024-11, with the labels that each got.

#66 Catch ClientConnectionError on config flow
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: bug, Semver-Patch

#64 Check for SysAP version 2.6.0 or newer
  README.md
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/const.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement, Semver-Minor

#68 Fix key error on user setup flow
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: bug, Semver-Patch

#69 Use term ABB-free@home
  README.md
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/button.py
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/const.py
  custom_components/abbfreeathome_ci/diagnostics.py
  custom_components/abbfreeathome_ci/event.py
  custom_components/abbfreeathome_ci/light.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/sensor.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/switch.py
  custom_components/abbfreeathome_ci/translations/en.json
  hacs.json
Labels: Semver-Patch

#81 Implement HeatingActuator
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/valve.py
Labels: enhancement, Semver-Minor

#84 Add new events/adjust, remove binary sensors
  README.md
  custom_components/abbfreeathome_ci/binary_sensor.py
  custom_components/abbfreeathome_ci/event.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement, Semver-Minor

#87 Implement lock-entity
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/lock.py
Labels: enhancement

#86 Add new select platform for forced options
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/select.py
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#93 Update strings.json with common keys
  custom_components/abbfreeathome_ci/strings.json
  custom_components/abbfreeathome_ci/translations/en.json
Labels: enhancement

#95 Revert has_entity_name=True
  custom_components/abbfreeathome_ci/button.py
  custom_components/abbfreeathome_ci/climate.py
  custom_components/abbfreeathome_ci/light.py
  custom_components/abbfreeathome_ci/lock.py
  custom_components/abbfreeathome_ci/manifest.json
  custom_components/abbfreeathome_ci/switch.py
  custom_components/abbfreeathome_ci/valve.py
Labels: bug

#96 Fix cover linting from Home Assistant
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/cover.py
Labels: bug

#98 Use the Home Assistant Client Session Object
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: enhancement

#103 Add PyPi packages to loggers manifest
  custom_components/abbfreeathome_ci/manifest.json
Labels: enhancement

#108 Use the FreeAtHomeSettings class to check SysAP compatibility.
  README.md
  custom_components/abbfreeathome_ci/config_flow.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: enhancement

#111 Remove virtual device support
  custom_components/abbfreeathome_ci/__init__.py
  custom_components/abbfreeathome_ci/manifest.json
Labels: bug
